version: 2
jobs:
  build:
    working_directory: ~/edustor-upload
    docker:
      - image: python:3.6
    environment:
      TERM: dumb
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - restore_cache:
          key: edustor-upload-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run: |
          pip3 install --cache-dir pip-cache -r requirements.txt
#          pip3 install --cache-dir pip-cache -r test-requirements.txt
#      - run: |
#          pytest
      - save_cache:
          key: edustor-upload-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - ~/edustor-upload/pip-cache
      - run:
          name: Trigger deploy
          command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  curl -u ${CIRCLE_API_TOKEN}: \
                    -d build_parameters[CIRCLE_JOB]=deploy_swarm \
                    https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
                fi
  deploy_swarm:
    branches:
      only:
        - master
    working_directory: ~/edustor-upload
    docker:
      - image: docker:git
    environment:
      IMAGE_NAME: quay.io/edustor/upload
      SWARM_CA_URL: https://wutiarn.keybase.pub/swarm/ca.pem
      SWARM_CERT_URL: https://wutiarn.keybase.pub/swarm/cert.pem
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker login -u="edustor+ci" -p="$REGISTRY_PASSWORD" quay.io
            docker build -t $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM  .
            docker tag $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM $IMAGE_NAME:latest
      - run:
          name: Push docker image
          command: |
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM
      - run:
          name: Deploy to swarm
          command: |
            mkdir -p /root/.docker
            curl -sSL $SWARM_CA_URL > /root/.docker/ca.pem
            curl -sSL $SWARM_CERT_URL > /root/.docker/cert.pem
            echo ${SWARM_KEY} | base64 -d > /root/.docker/key.pem
            export DOCKER_HOST=swarm.wutiarn.ru:2376
            export DOCKER_TLS_VERIFY=1
            docker --tlsverify --tlscacert /root/.docker/ca.pem \
              --tlscert /root/.docker/cert.pem --tlskey /root/.docker/key.pem \
              service update --with-registry-auth --image $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM sw0_edustor-upload